seqsense/aws-iot-device-sdk-go

device.go, device_test.go, go.mod, go.sum, sample/main.go
=> Make DeviceClient compatible with mqtt.Client interface

connection.go, debug.go, debug_test.go, device.go, sample/main.go
=> Control debug output by Option.Debug

awsiotprotocol/config.go, awsiotprotocol/loader.go, awsiotprotocol/mock.go, awsiotprotocol/mqtts.go, awsiotprotocol/wss.go, debug.go, device.go, options.go, pubqueue/drop_behavior.go, pubqueue/pubqueue.go, subqueue/subqueue.go
=> Add godoc comments

v2/connection.go, v2/connection_test.go
This PR use RWLock when accessing pubSubQueues.activeSubs map.
closes #36
=> Lock activeSubs map when accessing it

v2/connection_test.go, v2/device.go, v2/options.go
=> Add OnConnect handler

v2/awsiotprotocol/mock.go, v2/connection_test.go, v2/device.go, v2/options.go, v2/sample/main.go
=> Hide mqtt.ClientOptions from OnConnectionLost callback argument

renovate.json
Add local timezone setting to renovate.json
=> Add timezone setting to renovate

renovate.json
This PR is the same purpose as https://github.com/seqsense/s3sync/pull/16 to reduce frequency of creating Renovate PRs.
@t-asaka @at-wat 
Could you have a look at this in your spare time? thank you 😃
=> Update Renovate scheduling

dialer.go, dialer_test.go, go.mod
=> Bump module version to v4

awsiotdev_test.go
=> Add Device interface

tunnel/proxy.go, tunnel/tunnel.go
to use custom proxy server like https://github.com/seqsense/aws-iot-device-sdk-go/pull/81
=> tunnel: add options to change proxy endpoint and notify topic

tunnel/proxy.go, tunnel/proxy_test.go
=> tunnel: use io.Read/Write instead of websocket.Codec

tunnel/destination.go, tunnel/proxy.go, tunnel/proxy_test.go, tunnel/proxyio.go, tunnel/source.go, tunnel/tunnel.go
=> tunnel: add source mode proxy

tunnel/cmd/secure-tunnel-server/Dockerfile
=> tunnel: cache go modules on tunnel server image build

go.mod, go.sum
fix length encoding bug: https://github.com/at-wat/mqtt-go/pull/115
=> chore(deps): update at-wat/mqtt-go to v0.10.1

examples/jobs/.gitignore, examples/jobs/main.go, go.mod, go.sum, jobs/clienttoken.go, jobs/error.go, jobs/jobs.go, jobs/jobs_test.go, jobs/option.go, jobs/type.go
=> jobs: implement IoT Jobs

shadow/shadow_test.go, shadow/state.go, shadow/state_test.go
Error code is int on Thing Shadow.
(It's string on Jobs.)
=> shadow: fix error message type

examples/shadow/main.go, examples/shadow/shortprettydump.go, shadow/metadata.go, shadow/metadata_test.go, shadow/shadow.go, shadow/shadow_test.go, shadow/state.go
=> shadow: support metadata

shadow/diff.go, shadow/diff_test.go, shadow/option.go, shadow/shadow.go, shadow/shadow_test.go
=> shadow: incrementally send Report and Desire

examples/jobs/main.go, examples/shadow/main.go, examples/tunnel/main.go
=> Update examples to use mqtt.ServeMux

.github/workflows/ci.yml
=> Update Go version matrix

shadow/diff.go, shadow/diff_test.go
=> shadow: handle json tag in state struct

tunnel/destination.go, tunnel/proxy.go, tunnel/proxy_test.go, tunnel/source.go, tunnel/stat.go, tunnel/tunnel.go
Add API to get number of the connections.
=> tunnel: add connection statistics

renovate.json
=> Format renovate.json

.github/workflows/tunnel-server.yaml
- https://github.com/seqsense/sq-cloud-issues/issues/3147
=> Update aws-actions/configure-aws-credentials to v2
